/**
 * @name AuthActionTypes
 * @description Auth Action types for Login, Register, Request Password Change, Change Password and Logout
 */

export enum AuthActionTypes {
  LOGIN_USER = "LOGIN_USER",
  LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS",
  LOGIN_USER_FAILED = "LOGIN_USER_FAILED",
  REGISTER_USER = "REGISTER_USER",
  REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILED = "REGISTER_USER_FAILED",
  REQUEST_PASSWORD_CHANGE = "REQUEST_PASSWORD_CHANGE",
  REQUEST_PASSWORD_CHANGE_SUCCESS = "REQUEST_PASSWORD_CHANGE_SUCCESS",
  REQUEST_PASSWORD_CHANGE_FAILED = "REQUEST_PASSWORD_CHANGE_FAILED",
  CHANGE_PASSWORD = "CHANGE_PASSWORD",
  CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED",
  LOGOUT_USER = "LOGOUT_USER",
  LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS",
  LOGOUT_USER_FAILED = "LOGOUT_USER_FAILED",
}
